apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/labels: kubernetes.io/arch=amd64
    machine.openshift.io/GPU: "0"
    machine.openshift.io/memoryMb: "65536"
    machine.openshift.io/vCPU: "16"
  creationTimestamp: "2025-05-19T11:57:13Z"
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-kr6sr-msmkd
  name: cluster-kr6sr-msmkd-worker-us-east-2b-gpu
  namespace: openshift-machine-api
  resourceVersion: "12457"
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-kr6sr-msmkd
      machine.openshift.io/cluster-api-machineset: cluster-kr6sr-msmkd-worker-us-east-2b-gpu
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-kr6sr-msmkd
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-kr6sr-msmkd-worker-us-east-2b-gpu
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          ami:
            id: ami-078e26f293629fe91
          apiVersion: machine.openshift.io/v1beta1
          blockDevices:
          - ebs:
              encrypted: true
              iops: 0
              kmsKey:
                arn: ""
              volumeSize: 100
              volumeType: gp2
          capacityReservationId: ""
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-kr6sr-msmkd-worker-profile
          instanceType: g6e.4xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          metadataServiceOptions: {}
          placement:
            availabilityZone: us-east-2b
            region: us-east-2
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - cluster-kr6sr-msmkd-node
          - filters:
            - name: tag:Name
              values:
              - cluster-kr6sr-msmkd-lb
          subnet:
            filters:
            - name: tag:Name
              values:
              - cluster-kr6sr-msmkd-subnet-private-us-east-2b
          tags:
          - name: kubernetes.io/cluster/cluster-kr6sr-msmkd
            value: owned
          - name: Stack
            value: project ocp4-cluster-kr6sr
          - name: env_type
            value: ocp4-cluster
          - name: guid
            value: kr6sr
          - name: owner
            value: unknown
          - name: platform
            value: RHPDS
          - name: uuid
            value: 8994fd21-dcd6-53a5-8f77-d4abea805968
          userDataSecret:
            name: worker-user-data
