apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-instance
  namespace: openshift-nfd
spec:
  instance: ""
  topologyUpdater: false
  operand:
    image: registry.redhat.io/openshift4/ose-node-feature-discovery:v4.12
    servicePort: 12000